server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 192.168.116.130
      port: 8500
      discovery:
        hostname: 192.168.1.103
        service-name: ${spring.application.name}