server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.116.130:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719


#配置化url，只是为了方便程序中@value注解获取而已
service-url:
  nacos-user-service: http://nacos-payment-provider


#激活sentinel对feign的支持  默认false
feign:
  sentinel:
    enabled: true